In [1]:
from LS_AMG_RAG import utils
import pandas as pd
import numpy as np
from LS_AMG_RAG.rag_chain.multihop_rag import main as multihop_rag

In [2]:
dataset_name = "yixuantt/MultiHopRAG"
subset_name1 = "corpus"
df_corpus = multihop_rag.load_huggingface_dataset_to_dataframe(dataset_name, subset_name1)

In [6]:
df_corpus[:2]

,title,category,body,url,source,author,published_at
0,200+ of the best deals from Amazon's Cyber Mon...,entertainment,"Table of Contents Table of Contents Echo, Fire...",https://mashable.com/article/cyber-monday-deal...,Mashable,None,2023-11-27T08:45:59+00:00
1,ASX set to drop as Wall Street’s September slu...,business,"ETF provider Betashares, which manages $30 bil...",https://www.smh.com.au/business/markets/asx-se...,The Sydney Morning Herald,Stan Choe,2023-09-26T19:11:30+00:00

In [8]:
df_corpus.describe()

,title,category,body,url,source,author,published_at
count,609,609,609,609,609,545,609
unique,609,6,609,609,49,300,606
top,200+ of the best deals from Amazon's Cyber Mon...,sports,"Table of Contents Table of Contents Echo, Fire...",https://mashable.com/article/cyber-monday-deal...,Sporting News,Natasha Lomas,2023-10-20T21:30:28+00:00
freq,1,211,1,1,101,14,2

In [7]:
import spacy
nlp = spacy.load(r"../../metadata_extraction/custom_ner/output/model-best")
for index, row in df_corpus.iterrows():
    # text = read_markdown_files(root,file)
    filename = row['title']
    category = row['category']
    # embeddings = gemini_vector(text, filename)
    # print(row)
    keywords = utils.keyword_yake(row['body']) 
    metadata = utils.extract_metadata(row['body'],nlp) # need to figure out about duplicates
    people = metadata["Person"]
    org = metadata["Organization"]
    places = metadata["Places"]
    money = metadata["Money"]
    email = metadata["Email Id"]
    contact_number = metadata["Contact_Number"]
    dates_mentioned = utils.date_extraction(row['body'])
    flag="AI"
    print("Completed!")
    print(filename, category, keywords, people, org, places, money, email, contact_number, dates_mentioned)
    break
    # utils.insert_data_into_mongodb_collection(client, filename, category, embeddings, text, flag, keywords, people, org, places, money, email, contact_number, dates_mentioned)
    # print("Completed")

Completed!
200+ of the best deals from Amazon's Cyber Monday sale entertainment ['cyber monday deals', 'deals', 'cyber monday', 'contents table', 'latest cyber monday', 'cyber monday laptop', 'contents echo', 'apple deals', 'amazon', 'deals apple deals'] ['Fire'] [] [] ['$20', '$599.99', '$199', '$249', '$349', '$5.95', '$299.99', '$50.99', '$35.94', '$9', '$229.99', '$200', '$14.95'] [] ['+ free $'] []

In [10]:
print(df_corpus['body'][0])

Table of Contents Table of Contents Echo, Fire TV, and Kindle deals Apple deals TV deals Laptop deals Headphone and earbud deals Tablet deals Gaming deals Speaker deals Vacuum deals Kitchen deals Smart home deals Fitness deals Beauty tech deals Drone deals Camera deals Lego deals Gift card deals

UPDATE: Nov. 27, 2023, 5:00 a.m. EST This post has been updated with all of the latest Cyber Monday deals available at Amazon.

Amazon is dragging out the year's biggest shopping holiday(s) into 11 days of deals.

The retail giant began its Black Friday sale in the early morning of Friday, Nov. 17 (a week ahead of schedule) and was on top of making the switch to Cyber Monday language in the wee hours of Saturday, Nov. 25. Official Cyber Monday mode, which is currently on through Monday, Nov. 27, includes both a ton of deals carried over from Black Friday plus some new ones.

We're curating a running list of Amazon's best Cyber Weekend deals, spotlighting some of our favorites and noting when good deals inevitably sell out. Read on for the full rundown, and check back often: We're going to be updating this story incessantly as the sale continues, as well as our even bigger (if you can imagine) list of Cyber Monday deals across more retailers.

Note: All newly added deals are marked with a ✨, while deals with a 🔥 have dropped to an all-time low price. Amazon's invite-only deals for Prime members are marked with a 📨. Deals with a strikeout were either sold out or expired at the time of writing.

Echo, Fire TV, and Kindle deals

Why we like it

An Echo Show is a subtle yet game-changing addition to any room — and for less than $40 with this rollover Black Friday to Cyber Monday deal, there's little reason to not make your life easier. The smart screen responds to Alexa commands that are particularly handy when your hands are full, like asking for measurement conversions mid-cooking, checking the weather mid-rushing out the door, or turning off your smart lights with a sleeping kid in hand. Plus, it's got a 5.5-inch screen and better sound than its predecessor, making it perfect for watching videos or video calling friends and family.

More Amazon device and service deals

Amazon services

Audible Premium Plus — $5.95/month $14.95/month for four months (save $9/month; new customers only; get an additional $20 Audible credit)

Echo Buds

Echo smart displays

Echo smart speakers

Fire tablets

Fire TVs

Note: All Fire TVs come with a free 6-month subscription to MGM+ (a $35.94 value).

Fire TV streaming devices

eero

Kindles

Miscellaneous Amazon devices

Apple deals

Why we like it

Now that the 64GB 9th generation iPad has been going in and out of stock (you might be able to find it on sale for $229.99), our new favorite iPad deal at Amazon is the 10th generation 64GB model for $349. Compared to the 9th gen, the 10th gen classic iPad has a slightly bigger screen that's now also a Liquid Retina display (10.9 inches versus 10.2 inches), a faster A14 Bionic chip for smoother multitasking, and USB-C charging.

More Apple deals

AirPods

MacBook

Mac

iPad

Apple Watch

TV deals

Why we like it

This 65-inch Fire TV from Amazon hit its lowest ever price this month, and we're not mad about it. With a 66 percent five-star review rating, it's got much to love: Including stunning 4K QLED resolution, adaptive brightness that adjusts to the lighting of your room, the ability to project famous art or personal pics on it when not streaming anything, and, of course, that quintessential Alexa voice control.

More TV deals

43 to 55 inches

65 inches

75 to 85 inches

Laptop deals

Why we like it

MacBooks aside (which are all listed above in the Apple section), another stellar Cyber Monday laptop deal at Amazon is the lightweight Microsoft Surface Laptop Go 3 for $599.99. This 25% discount drops the 2023 version to the regular asking price of our favorite budget laptop, the older Surface Go 2. Compared to the Go 2, the Go 3's Intel Core i5 processor is 12th gen versus the Go 2's 11th gen, harnessing better speeds and solid power for most everyday work or school tasks. On the outside, the Go 3 is definitely giving MacBook Air — the main difference being that the Go 3's screen is a touchscreen.

More laptop deals

Traditional laptops

2-in-1 laptops

Chromebooks

Gaming laptops

Headphone and earbud deals

Why we like it

Narrowing down a headphones upgrade from so many on-sale options is less overwhelming when you've confirmed that you want to stick with a super premium, super reputable brand like Bose — but also that you want to stick to a budget. There's only one pair of Bose over-ear headphones you can grab for just under $200, and that's the QuietComfort 45s at a record-low price of $199. This classic pair secures top-of-the-line ANC, 20 hours of battery life, and all-day comfort for less than half of the AirPods Max's sale price.

More headphone and earbud deals

Headphones

Earbuds

Tablet deals

Gaming deals

Gaming headsets

Mashable Deals Want more hand-picked deals in your inbox? Sign up for Mashable's daily Deals newsletter. Loading... Sign Me Up By signing up you agree to our Terms of Use and Privacy Policy Thanks for signing up!

Gaming mice

Gaming keyboards

VR headsets

Meta Quest 2 — $249 $299.99 (save $50.99) + free $50 Amazon credit with code META50 🔥

Speaker deals

Vacuum deals

Cordless vacuums

Robot vacuums and vacuum/mop hybrids

Kitchen deals

Pizza ovens

Sparkling water makers

Toaster ovens

Smart home deals

Note: Echo devices are listed above under "Amazon device and service deals."

Blink

Chromecast

Google Nest

Fitness deals

Smartwatches and fitness trackers

Note: Apple Watches are listed above under "Apple deals."

Beauty tech deals

Drone deals

Camera deals

GoPro

Lego deals

Gift card deals